In [5]:
import pandas as pd
import mysql.connector as mysql
import re
import numpy as np

db = mysql.connect(
    host="localhost",
    user="root",
    password="password",
    port="3306",
    database="serlo"
)


def query(sql):
    c = db.cursor()
    c.execute(sql)
    return c.fetchall()


def comment_on_own_page(user_id):
    # select user.id, comment.content from comment join user on user.id = comment.author_id where comment.uuid_id = user.id;
    return len(query(f"""select comment_vote.user_id
    from comment_vote
    inner join comment
    on comment.id = comment_vote.comment_id
    where comment_vote.user_id = comment.author_id and comment_vote.user_id = {user_id}""")) > 0
    
    
df = pd.read_sql("""
    Select
        user.id,
        user.username,
        user.description,
        user.date,
        sum(events.edits) as edits,
        sum(events.reviews) as reviews,
        sum(events.comments) as comments,
        sum(events.taxonomy) as taxonomy
    From (
        SELECT
            IF(event_log.event_id = 5, 1, 0) as edits,
            IF(event_log.event_id in (6,11), 1, 0) as reviews,
            IF(event_log.event_id in (8,9,14,16), 1, 0) as comments,
            IF(event_log.event_id in (1,2,12,15,17), 1, 0) as taxonomy,
            event_log.actor_id
        FROM event_log
        WHERE event_log.event_id IN (5,6,11,8,9,14,16,1,2,12,15,17)
    ) events
    right join user on user.id = events.actor_id
    group by user.id
""", db)
df.fillna(0, inplace=True)
df["comment_on_own_page"] = df["id"].map(comment_on_own_page)  
df_potential_bot = df[
    ((df["edits"] + df["reviews"] + df["taxonomy"] == 0) & (df["comments"] > 0) & df["comment_on_own_page"])
].copy()
df_potential_bot.sort_values(["id"], inplace=True)
df_potential_bot.to_csv("/tmp/2022-21-03users_with_comments_on_own_page.csv")
df_potential_bot

,id,username,description,date,edits,reviews,comments,taxonomy,comment_on_own_page
1856,39586,Beachy,NULL,2015-04-24 09:01:24,0.0,0.0,1.0,0.0,True
2250,47567,TheGenius,NULL,2015-10-04 09:22:25,0.0,0.0,1.0,0.0,True
2573,51931,rmg,,2016-02-24 14:25:17,0.0,0.0,2.0,0.0,True
2661,54733,WolfOliver,NULL,2016-03-18 10:33:11,0.0,0.0,3.0,0.0,True
2990,61630,amitsulu,NULL,2016-08-30 06:49:01,0.0,0.0,3.0,0.0,True
3082,64299,DoDoR,NULL,2016-10-05 13:33:36,0.0,0.0,1.0,0.0,True
3691,67431,HornyUnicorn,NULL,2016-12-31 15:53:59,0.0,0.0,11.0,0.0,True
3767,68040,checker001,NULL,2017-01-20 07:56:31,0.0,0.0,1.0,0.0,True
3976,69781,malte5101,NULL,2017-02-28 07:33:52,0.0,0.0,13.0,0.0,True
4275,73761,Sarittaa04,NULL,2017-04-04 23:30:20,0.0,0.0,12.0,0.0,True
4532,75017,TYP,NULL,2017-04-25 07:00:46,0.0,0.0,2.0,0.0,True
4775,80095,Hans_Norbert,NULL,2017-07-12 08:22:16,0.0,0.0,4.0,0.0,True
4778,80098,TheCreator,NULL,2017-07-12 08:23:47,0.0,0.0,3.0,0.0,True
4779,80100,SchnelleGazelle,NULL,2017-07-12 08:24:09,0.0,0.0,5.0,0.0,True
4780,80101,TheDestroyer,NULL,2017-07-12 08:24:10,0.0,0.0,3.0,0.0,True
4783,80105,Nikkz,NULL,2017-07-12 08:25:43,0.0,0.0,7.0,0.0,True
5646,91306,abcdef,NULL,2017-11-11 18:06:19,0.0,0.0,2.0,0.0,True
5690,91585,levinkn,NULL,2017-11-19 13:45:08,0.0,0.0,5.0,0.0,True
6187,94220,xXMateSkillaXx,NULL,2018-01-18 07:46:00,0.0,0.0,4.0,0.0,True
7480,109410,Elo-Student,NULL,2018-06-19 20:36:53,0.0,0.0,2.0,0.0,True
8924,122039,Magicadi,NULL,2018-10-28 10:54:46,0.0,0.0,1.0,0.0,True
8981,122692,I_Schrott,NULL,2018-11-05 08:25:36,0.0,0.0,3.0,0.0,True
9003,123040,yonazu,NULL,2018-11-07 12:11:51,0.0,0.0,5.0,0.0,True
9860,126305,Frodlovingo,NULL,2018-12-12 16:48:45,0.0,0.0,1.0,0.0,True
10188,126874,mathegenie25,"{""plugin"":""rows"",""state"":[{""plugin"":""text"",""st...",2018-12-18 08:50:33,0.0,0.0,1.0,0.0,True
10438,127445,Maiki,NULL,2019-01-02 16:50:26,0.0,0.0,2.0,0.0,True
10543,129438,DerPro_YT,NULL,2019-01-22 14:05:10,0.0,0.0,8.0,0.0,True
10603,129787,veganz,NULL,2019-02-05 12:48:29,0.0,0.0,12.0,0.0,True
10797,134059,Leinad,NULL,2019-03-26 14:51:48,0.0,0.0,5.0,0.0,True
10835,134936,Ennsen,NULL,2019-04-01 21:04:13,0.0,0.0,1.0,0.0,True
10912,135976,Nici01,NULL,2019-04-16 15:18:03,0.0,0.0,2.0,0.0,True
10962,136559,ichrasierabi2019oderauchnicht,NULL,2019-05-01 16:34:32,0.0,0.0,10.0,0.0,True
11165,139151,DerCooleJunge123,NULL,2019-06-20 18:32:25,0.0,0.0,2.0,0.0,True
11426,144296,Gerhard,NULL,2019-09-16 12:25:34,0.0,0.0,1.0,0.0,True
11735,147127,Kre18,NULL,2019-11-17 08:51:47,0.0,0.0,3.0,0.0,True
11753,147214,reem_aag,NULL,2019-11-20 08:02:16,0.0,0.0,2.0,0.0,True
11765,147227,The_FLASH,NULL,2019-11-20 08:17:54,0.0,0.0,7.0,0.0,True
11809,147559,Moke,NULL,2019-11-28 09:14:34,0.0,0.0,1.0,0.0,True
12445,156377,brot,NULL,2020-03-19 08:48:15,0.0,0.0,1.0,0.0,True
12545,157060,okan2907,NULL,2020-03-23 15:22:36,0.0,0.0,1.0,0.0,True
12678,158699,Cringe,NULL,2020-03-30 17:38:14,0.0,0.0,4.0,0.0,True
12983,163786,Berti,NULL,2020-04-23 20:54:55,0.0,0.0,2.0,0.0,True
13012,164302,G-Toss,NULL,2020-04-27 08:41:46,0.0,0.0,3.0,0.0,True
13084,165081,pajbo,NULL,2020-05-03 11:57:36,0.0,0.0,2.0,0.0,True
13278,168347,wicki,NULL,2020-05-24 15:39:56,0.0,0.0,1.0,0.0,True
13322,169154,drazen,NULL,2020-06-01 11:07:32,0.0,0.0,1.0,0.0,True
13736,177397,nikitarhode143,NULL,2020-09-09 21:34:34,0.0,0.0,1.0,0.0,True
13834,179044,robinsmithsters,NULL,2020-09-25 11:46:22,0.0,0.0,3.0,0.0,True
13987,181284,vluxus,NULL,2020-10-19 21:37:59,0.0,0.0,1.0,0.0,True
14204,184177,FW,NULL,2020-11-17 17:09:40,0.0,0.0,2.0,0.0,True
14620,190926,prasraph,NULL,2021-01-19 10:45:50,0.0,0.0,2.0,0.0,True
14895,195987,Vanesa,NULL,2021-02-26 09:01:36,0.0,0.0,1.0,0.0,True
14949,196921,travomojo,NULL,2021-03-04 13:20:19,0.0,0.0,2.0,0.0,True
15337,206474,Grammhil,NULL,2021-04-26 10:54:04,0.0,0.0,2.0,0.0,True
15384,208253,Matheguru,NULL,2021-05-01 17:23:49,0.0,0.0,3.0,0.0,True
15413,208830,WarumIstDaEinGleichheitszeichen,NULL,2021-05-04 23:35:35,0.0,0.0,2.0,0.0,True